=== lokeshsp/PivotalTracker/schemas/integration-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "import_api_url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "project_id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "can_import" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "base_url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "is_other" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "story_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "active" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updated_at" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== lokeshsp/PivotalTracker/examples/lables-example.json
[
  {
    "kind" : "label" ,
    "id" : 2008 ,
    "project_id" : 99 ,
    "name" : "plans" ,
    "created_at" : "2014-07-22T12:00:00Z" ,
    "updated_at" : "2014-07-22T12:00:00Z"
  } , {
    "kind" : "label" ,
    "id" : 2007 ,
    "project_id" : 99 ,
    "name" : "rebel bases" ,
    "created_at" : "2014-07-22T12:00:00Z" ,
    "updated_at" : "2014-07-22T12:00:00Z"
  }
]

=== lokeshsp/PivotalTracker/examples/integrations-example.json
[
  {
    "kind" : "other_integration" ,
    "import_api_url" : "http://localhost:3000/starwars.xml" ,
    "id" : 30 ,
    "project_id" : 99 ,
    "can_import" : true ,
    "base_url" : "http://localhost:3000" ,
    "is_other" : true ,
    "story_name" : "item" ,
    "name" : "Sounder Flats Computer Complex" ,
    "active" : true ,
    "created_at" : "2014-08-12T12:00:00Z" ,
    "updated_at" : "2014-08-12T12:00:00Z"
  }
]
