=== lokeshsp/PivotalTracker/schemas/me-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "api_token" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "email" : {
      "type" : "string" ,
      "required" : false
    } ,
    "has_google_identity" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "initials" : {
      "type" : "string" ,
      "required" : false
    } ,
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "projects" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "kind" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "project_id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "project_name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "project_color" : {
              "type" : "string" ,
              "required" : false
            } ,
            "role" : {
              "type" : "string" ,
              "required" : false
            } ,
            "last_viewed_at" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "receives_in_app_notifications" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "time_zone" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "kind" : {
          "type" : "string" ,
          "required" : false
        } ,
        "olson_name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "offset" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "updated_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "username" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== lokeshsp/PivotalTracker/examples/me-example.json
{
  "api_token" : "VadersToken" ,
  "created_at" : "2014-07-22T12:00:05Z" ,
  "email" : "vader@deathstar.mil" ,
  "has_google_identity" : false ,
  "id" : 101 ,
  "initials" : "DV" ,
  "kind" : "me" ,
  "name" : "Darth Vader" ,
  "projects" : [
    {
      "kind" : "membership_summary" ,
      "id" : 108 ,
      "project_id" : 98 ,
      "project_name" : "Learn About the Force" ,
      "project_color" : "8100ea" ,
      "role" : "owner" ,
      "last_viewed_at" : "2014-07-22T12:00:00Z"
    } , {
      "kind" : "membership_summary" ,
      "id" : 101 ,
      "project_id" : 99 ,
      "project_name" : "Death Star" ,
      "project_color" : "8100ea" ,
      "role" : "member" ,
      "last_viewed_at" : "2014-07-22T12:00:00Z"
    }
  ] ,
  "receives_in_app_notifications" : true ,
  "time_zone" : {
    "kind" : "time_zone" ,
    "olson_name" : "America/Los_Angeles" ,
    "offset" : "-08:00"
  } ,
  "updated_at" : "2014-07-22T12:00:10Z" ,
  "username" : "vader"
}
