=== lokeshsp/PivotalTracker/schemas/notification-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "action" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "message" : {
      "type" : "string" ,
      "required" : false
    } ,
    "new_attachment_count" : {
      "type" : "number" ,
      "required" : false
    } ,
    "notification_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "performer" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "kind" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "number" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "project" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "kind" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "number" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "read_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "story" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "kind" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "number" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "updated_at" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== lokeshsp/PivotalTracker/examples/notification-example.json
{
  "action" : "ownership" ,
  "created_at" : "2014-07-22T12:00:00Z" ,
  "id" : 21 ,
  "kind" : "notification" ,
  "message" : "Wilhuff Tarkin has made you an owner of this story:" ,
  "new_attachment_count" : 0 ,
  "notification_type" : "story" ,
  "performer" : {
    "kind" : "person" ,
    "id" : 102 ,
    "name" : "Wilhuff Tarkin"
  } ,
  "project" : {
    "kind" : "project" ,
    "id" : 99 ,
    "name" : "Death Star"
  } ,
  "read_at" : "2014-07-22T12:00:05Z" ,
  "story" : {
    "kind" : "story" ,
    "id" : 558 ,
    "name" : "All exhaust ports should be shielded"
  } ,
  "updated_at" : "2014-07-22T12:00:05Z"
}
