=== lokeshsp/PivotalTracker/schemas/person-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "email" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "initials" : {
      "type" : "string" ,
      "required" : false
    } ,
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "username" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== lokeshsp/PivotalTracker/examples/persons-example.json
[
  {
    "kind" : "person" ,
    "id" : 100 ,
    "name" : "Emperor Palpatine" ,
    "email" : "emperor@galacticrepublic.gov" ,
    "initials" : "EP" ,
    "username" : "palpatine"
  } , {
    "kind" : "person" ,
    "id" : 103 ,
    "name" : "Moradmin Bast" ,
    "email" : "bast@deathstar.mil" ,
    "initials" : "MB" ,
    "username" : "bast"
  }
]
