=== lokeshsp/PivotalTracker/schemas/projectReq-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "account_id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "atom_enabled" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "automatic_planning" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "bugs_and_chores_are_estimatable" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "enable_incoming_emails" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "enable_tasks" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "initial_velocity" : {
      "type" : "number" ,
      "required" : false
    } ,
    "iteration_length" : {
      "type" : "number" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "number_of_done_iterations_to_show" : {
      "type" : "number" ,
      "required" : false
    } ,
    "point_scale" : {
      "type" : "string" ,
      "required" : false
    } ,
    "public" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "start_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "time_zone" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "kind" : {
          "type" : "string" ,
          "required" : false
        } ,
        "olson_name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "offset" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "velocity_averaged_over" : {
      "type" : "number" ,
      "required" : false
    } ,
    "week_start_day" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== lokeshsp/PivotalTracker/examples/projectReq-example.json
{
  "account_id" : 100 ,
  "atom_enabled" : false ,
  "automatic_planning" : true ,
  "bugs_and_chores_are_estimatable" : false ,
  "enable_incoming_emails" : true ,
  "enable_tasks" : true ,
  "initial_velocity" : 10 ,
  "iteration_length" : 1 ,
  "name" : "Executioner" ,
  "number_of_done_iterations_to_show" : 12 ,
  "point_scale" : "0,1,2,3" ,
  "public" : false ,
  "start_date" : "2014-07-22T12:00:00Z" ,
  "time_zone" : {
    "kind" : "time_zone" ,
    "olson_name" : "America/Los_Angeles" ,
    "offset" : "-07:00"
  } ,
  "velocity_averaged_over" : 3 ,
  "week_start_day" : "Monday"
}
